<a href="https://colab.research.google.com/github/kristinanett/02456-deep-learning-with-PyTorch/blob/master/3_Feedforward_PyTorch/3.1-what-is-pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Credits

This is heavily influenced or copied from https://github.com/pytorch/tutorials

# What is PyTorch?

> **NOTE** In the last part of this lab cuda is used. If you have a cuda enabled machine, read the README.md in the root of this repo on how to use nvidia-docker.


It’s a Python based scientific computing package targeted at two sets of
audiences:
-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed


# Getting Started

In this lab you will get a quick start on what pytorch is and how to use it.

## 1. Tensors

Tensors are similar to numpy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

In [2]:
import torch

Construct a 5x3 matrix, uninitialized

In [3]:
x = torch.Tensor(5, 3)
print(x)

tensor([[1.3495e+30, 3.0962e-41, 3.7835e-44],
        [0.0000e+00,        nan, 3.0962e-41],
        [1.3733e-14, 6.4069e+02, 4.3066e+21],
        [1.1824e+22, 4.3066e+21, 6.3828e+28],
        [3.8016e-39, 3.0962e-41, 3.5148e+29]])


Construct a randomly initialized matrix

In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.3878, 0.5127, 0.1098],
        [0.8145, 0.6383, 0.2991],
        [0.4723, 0.1406, 0.8021],
        [0.9423, 0.9877, 0.7174],
        [0.2497, 0.6621, 0.6350]])


Get its size

In [5]:
print(x.size())

torch.Size([5, 3])


**NOTE** `torch.Size` is in fact a tuple, so it supports the same operations

In [6]:
x[1:3] = 2
print(x)

tensor([[0.3878, 0.5127, 0.1098],
        [2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000],
        [0.9423, 0.9877, 0.7174],
        [0.2497, 0.6621, 0.6350]])


# Assignment

Make use of the pytorch docs <http://pytorch.org/docs/torch>
1. Make a tensor of size (2, 17)
2. Make a torch.FloatTensor of size (3, 1)
3. Make a torch.LongTensor of size (5, 2, 1)
  - fill the entire tensor with 7s
4. Make a torch.ByteTensor of size (5,)
  - fill the middle 3 indices with ones such that it records [0, 1, 1, 1, 0]

In [7]:
#Tensor of size (2, 17)

t = torch.Tensor(2, 17)
print(t)

tensor([[1.3020e+30, 3.0962e-41, 0.0000e+00, 0.0000e+00, 1.4013e-45, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         1.3474e+30, 3.0962e-41, 0.0000e+00, 0.0000e+00, 1.4013e-45],
        [0.0000e+00, 4.2039e-45, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 1.4013e-45,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [8]:
#Float tensor of size (3,1)

t = torch.FloatTensor(3,1)
print(t)

tensor([[1.3495e+30],
        [3.0962e-41],
        [2.3694e-38]])


In [9]:
# Long tensor of size (5, 2, 1) and change all values to 7

t = torch.LongTensor(5, 2, 1)
print(t)
print()

t[:,:,:] = 7
print(t)

tensor([[[94899207126400],
         [  210453397554]],

        [[  206158430253],
         [  193273528377]],

        [[  219043332145],
         [  210453397588]],

        [[  249108103218],
         [  214748364851]],

        [[  227633266746],
         [  197568495664]]])

tensor([[[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]]])


In [10]:
#Make a torch.ByteTensor of size (5,) + fill the middle 3 indices with ones such that it records [0, 1, 1, 1, 0]

t = torch.ByteTensor(5) 
print(t)

t[1:4] = 1
print(t)

tensor([ 64,  69, 136, 113,  79], dtype=torch.uint8)
tensor([64,  1,  1,  1, 79], dtype=torch.uint8)


## 2. Operations
There are multiple syntaxes for operations. Let's see addition as an example:

### 2.1 Addition: syntax 1

In [11]:
y = torch.rand(5, 3)
print(x + y)

tensor([[0.8678, 1.1455, 0.2772],
        [2.0177, 2.1097, 2.7128],
        [2.2940, 2.0204, 2.7143],
        [1.0639, 1.7897, 0.9001],
        [0.5748, 1.0544, 1.1323]])


### 2.2 Addition: syntax 2

In [12]:
print(torch.add(x, y))

tensor([[0.8678, 1.1455, 0.2772],
        [2.0177, 2.1097, 2.7128],
        [2.2940, 2.0204, 2.7143],
        [1.0639, 1.7897, 0.9001],
        [0.5748, 1.0544, 1.1323]])


### 2.3 Addition: giving an output tensor

In [13]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[0.8678, 1.1455, 0.2772],
        [2.0177, 2.1097, 2.7128],
        [2.2940, 2.0204, 2.7143],
        [1.0639, 1.7897, 0.9001],
        [0.5748, 1.0544, 1.1323]])


### 2.4 Addition: in-place

adds `x`to `y`

In [14]:
y.add_(x)
print(y)

tensor([[0.8678, 1.1455, 0.2772],
        [2.0177, 2.1097, 2.7128],
        [2.2940, 2.0204, 2.7143],
        [1.0639, 1.7897, 0.9001],
        [0.5748, 1.0544, 1.1323]])


**NOTE** Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

You can use standard numpy-like indexing with all bells and whistles!

In [15]:
print(x[:, 1])

tensor([0.5127, 2.0000, 2.0000, 0.9877, 0.6621])


**Read later** 100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc are described here <http://pytorch.org/docs/torch>

# Assignment

1. multiplication of two tensors (see [torch.Tensor.mul](http://pytorch.org/docs/master/tensors.html#torch.Tensor.mul))
2. do the same, but inplace
3. division of two tensors (see [torch.Tensor.div](http://pytorch.org/docs/master/tensors.html#torch.Tensor.div))
4. perform a matrix multiplication of two tensors of size (2, 4) and (4, 2)

In [16]:
#Tensor multiplication 
w = torch.full((3, 3), 2)
q = torch.full((3, 3), 5)

out = torch.mul(w, q)
print(out)

tensor([[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]])


In [17]:
#Tensor in-place multiplication
w = torch.full((3, 3), 2)
q = torch.full((3, 3), 5)

q.mul_(w)
print(q)

tensor([[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]])


In [18]:
#Tensor division
w = torch.full((3, 3), 10)
q = torch.full((3, 3), 5)

out = torch.div(w, q)
print(out)

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])


In [19]:
#Matrix multiplication

w = torch.full((2, 4), 2)
q = torch.full((4, 2), 5)

out = torch.matmul(w, q)
print(out)


tensor([[40, 40],
        [40, 40]])


## 3. Numpy Bridge

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

### 3.1 Converting torch Tensor to numpy Array

In [20]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [21]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.

In [22]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### 3.2 Converting numpy Array to torch Tensor

See how changing the np array changed the torch Tensor automatically

In [23]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# Assignment

1. create a tensor of size (5, 2) containing ones
2. now convert it to a numpy array
3. now convert it back to a torch tensor

In [24]:
#Tensor of 1s into a np array and back to tensor

t = torch.ones(5, 2)
print(t)

a = t.numpy()
print(a)

t_again = torch.from_numpy(a)
print(t_again)


tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])


All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

## 4 CUDA Tensors

Tensors can be moved onto GPU using the `.cuda` function.
This is not necessary, but check the `README.md` for details on how to use a GPU with docker.

In [25]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    z = x + y
    # notice that the tensors are now of type torch.cuda.FloatTensor (notice the cuda in there)
    # this is meant as a tensor to be run on the GPU.
    # the .cuda() does this to any parameter it is applied to
    print(x)
    print(y)
    print(z)
else:
    print("CUDA not available on your machine.")

tensor([[0.3878, 0.5127, 0.1098],
        [2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000],
        [0.9423, 0.9877, 0.7174],
        [0.2497, 0.6621, 0.6350]], device='cuda:0')
tensor([[0.8678, 1.1455, 0.2772],
        [2.0177, 2.1097, 2.7128],
        [2.2940, 2.0204, 2.7143],
        [1.0639, 1.7897, 0.9001],
        [0.5748, 1.0544, 1.1323]], device='cuda:0')
tensor([[1.2556, 1.6582, 0.3870],
        [4.0177, 4.1097, 4.7128],
        [4.2940, 4.0204, 4.7143],
        [2.0062, 2.7774, 1.6176],
        [0.8245, 1.7165, 1.7672]], device='cuda:0')
